//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserSource
    {
        public System.Guid AppUserSourceId { get; set; }
        public System.Guid AppUserId { get; set; }
        public int SourceId { get; set; }
        public string Credentials { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Source Source { get; set; }
    }
}
