//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public System.Guid ContactDetailId { get; set; }
        public System.Guid ContactId { get; set; }
        public int DetailId { get; set; }
        public string DetailValue { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Detail Detail { get; set; }
    }
}
