//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactEmailAddress
    {
        public System.Guid ContactEmailAddressId { get; set; }
        public System.Guid ContactId { get; set; }
        public System.Guid EmailAddressId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual EmailAddress EmailAddress { get; set; }
    }
}
