//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailType
    {
        public DetailType()
        {
            this.Details = new HashSet<Detail>();
        }
    
        public int DetailTypeId { get; set; }
        public Nullable<int> ParentDetailType { get; set; }
        public string DetailTypeName { get; set; }
    
        public virtual ICollection<Detail> Details { get; set; }
    }
}
