//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public Detail()
        {
            this.ContactDetails = new HashSet<ContactDetail>();
        }
    
        public int DetailId { get; set; }
        public int DetailTypeId { get; set; }
        public string DetailName { get; set; }
    
        public virtual ICollection<ContactDetail> ContactDetails { get; set; }
        public virtual DetailType DetailType { get; set; }
    }
}
