//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public System.Guid DeviceId { get; set; }
        public int DeviceTypeId { get; set; }
        public System.Guid AppUserId { get; set; }
        public string UDID { get; set; }
        public Nullable<bool> DefaultCallReceiver { get; set; }
        public Nullable<bool> DefaultDataReceiver { get; set; }
        public Nullable<int> DataReceiverSequence { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual DeviceType DeviceType { get; set; }
    }
}
