//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAddress
    {
        public EmailAddress()
        {
            this.ContactEmailAddresses = new HashSet<ContactEmailAddress>();
        }
    
        public System.Guid EmailAddressId { get; set; }
        public string ProvidedEmailAddress { get; set; }
    
        public virtual ICollection<ContactEmailAddress> ContactEmailAddresses { get; set; }
    }
}
