//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public PhoneNumber()
        {
            this.ContactPhoneNumbers = new HashSet<ContactPhoneNumber>();
        }
    
        public System.Guid PhoneNumberId { get; set; }
        public long PhoneNumber1 { get; set; }
        public string Display { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual ICollection<ContactPhoneNumber> ContactPhoneNumbers { get; set; }
        public virtual Country Country { get; set; }
    }
}
