//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public System.Guid TokenId { get; set; }
        public System.Guid AppUserId { get; set; }
        public System.DateTime IssueDateTime { get; set; }
        public int Validity { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
